package com.vizuri.fantasy.domain;

import java.math.BigDecimal;

rule "CreateWeeklyStatisticHolder"
	dialect "mvel"
	when
		$playStatistic : PlayStatistic( $week : week, $year : year, $playerId : playerId, $statisticType : statisticType)
		not PlayerWeeklyStatistic ( week == $week, year == $year, playerId == $playerId, statisticType == $statisticType )
	then
		PlayerWeeklyStatistic weeklyStat = new PlayerWeeklyStatistic();
		weeklyStat.setWeek( $week );
		weeklyStat.setYear( $year );
		weeklyStat.setPlayerId( $playerId );
		weeklyStat.setStatisticType( $statisticType );
		insert( weeklyStat );
		System.err.println("Created weekly stat: " + weeklyStat.toString() );
end

rule "AddStatToWeeklyHolder"
	when
		$playStatistic : PlayStatistic( $week : week, $year : year, $playerId : playerId, $statisticType : statisticType)
		$weeklyStat : PlayerWeeklyStatistic ( week == $week, year == $year, playerId == $playerId, statisticType == $statisticType )
	then
		$weeklyStat.setAddStatisticValue( $playStatistic.getStatisticValue() );
		update( $weeklyStat );
		System.err.println("Updated weekly stat: " + $weeklyStat.toString() );
end

rule "CreateWeeklyScoreHolder"
	dialect "mvel"
	when
		$playScore : PlayScore( $week : week, $year : year, $playerId : playerId, $rulesetId : rulesetId )
		not PlayerWeeklyScore( week == $week, year == $year, playerId == $playerId, rulesetId == $rulesetId )
	then
		PlayerWeeklyScore weeklyScore = new PlayerWeeklyScore();
		weeklyScore.setWeek($week);
		weeklyScore.setYear($year);
		weeklyScore.setPlayerId($playerId);
		weeklyScore.setRulesetId($rulesetId);
		insert(weeklyScore);
		System.err.println("Created weekly score: " + weeklyScore.toString() );
end

rule "AddScoreToWeeklyTotal"
	when
		$playScore : PlayScore( $week : week, $year : year, $playerId : playerId, $rulesetId : rulesetId )
		$weeklyScore : PlayerWeeklyScore( week == $week, year == $year, playerId == $playerId, rulesetId == $rulesetId )
	then
		$weeklyScore.addScore( $playScore.getScore());
		System.err.println("Updated weekly score: " + $weeklyScore.toString() );
end


