package com.vizuri.fantasy_football_brms;
	
import com.vizuri.rules.domain.Violation;
import java.util.ArrayList;
import com.vizuri.rules.domain.FantasyTeam;
import com.vizuri.rules.domain.Severity;
import com.vizuri.rules.domain.FantasyLeague;
	
	rule "Fantasy League Size Validator"
	    dialect "mvel"
	    when
	        $league:FantasyLeague()
	        ArrayList( size > 0 && (size < 3 || size > 10) ) from collect ( FantasyTeam(leagueId == $league.id) )
	    then
	         Violation $vio = new Violation();
	         $vio.setDetails( "Invalid Fantasy Team Size" );
	         $vio.setSeverity( Severity.ERROR );
	         $vio.setTitle( "Invalid Fantasy League" );
	         $league.getViolationList().add($vio);
	         insert($vio);
	end

