package com.vizuri.fantasy_football_brms;
import com.vizuri.rules.domain.FantasyTeam;
import com.vizuri.rules.domain.Player;
import com.vizuri.rules.domain.Violation;
import com.vizuri.rules.domain.Severity;
import java.util.ArrayList;

rule "Fantasy Team Size Valid"
	dialect "mvel"
	when
	 	$team:FantasyTeam();
		ArrayList( size > 0 && (size < 5 || size > 15) ) from collect ( Player(fantasyTeamId == $team.id) )
	then
		Violation $vio = new Violation();
		$vio.setDetails( "Invalid Roster Size" );
		$vio.setSeverity( Severity.ERROR );		
		$vio.setTitle( $team.getName() );
		$team.getViolationList().add($vio);
		insert( $vio );
end
